# Fichier de configuration de l'application
# Les sections sont définies entre crochets []
# Les paramètres sont définis sous la forme clé = valeur
# À modifier selon les besoins

[DEFAULT]
url = https://172.18.0.2:443/archive.zip
sql_filename = dumpfile.sql
retention_days = 7  
enable_retention = True  

[SFTP]
host = 172.18.0.3
port = 22
username = antho
password = sylvie-alexis
remote_directory = data

[EMAIL]
enable_email = True
use_tls = False
smtp_server = smtp.gmail.com
smtp_port = 465
smtp_username = silvaraynal@gmail.com
smtp_password = vgjj mdaw imii vzkb
sender_email = silvaraynal@gmail.com
recipient_email = silvaraynal@gmail.com, ***@***.com
subject_success = Sauvegarde réussie
subject_failure = Échec de la sauvegarde
attach_log = True

[LOGGING]
log_file = logs/archive.log