[DEFAULT]
url = http://localhost:8080/archive.zip
sql_filename = sample-mpg-file.mpg
# Durée de conservation des fichiers en jours
retention_days = 7  
# Activer l'historisation des versions
enable_retention = True  

[SFTP]
host = localhost
port = 22
username = antho
password = sylvie-alexis
sql_filename_remote = sample-mpg-file.mpg
# Pour Windows
#remote_directory = C:/Users/antho/Archivage

# Pour Linux
remote_directory = data

[EMAIL]
enable_email = False
smtp_host = smtp.gmail.com
smtp_port = 465
smtp_username = silvaraynal@gmail.com
smtp_password = vgjj mdaw imii vzkb
sender_email = silvaraynal@gmail.com
recipient_email = silvaraynal@gmail.com
subject_success = Sauvegarde réussie
subject_failure = Échec de la sauvegarde
attach_log = True
use_ssl = True

[LOGGING]
log_file = logs/archivage.log
