[DEFAULT]
url = http://localhost/archive.zip
sql_filename = sample-mpg-file.mpg
retention_days = 30

[SFTP]
host = localhost
port = 22
username = antho
password = sylvie-alexis
; Pour Windows
;remote_directory = C:/Users/antho/Archivage

; Pour Linux
remote_directory = /home/antho/data

[LOGGING]
log_file = logs/archivage.log
